### ISSUE TITLE
Issue with Werkzeug package upgrade

### ISSUE THREAD

**Issue by DeanRIowa** [rhasspy/piper-recording-studio#11]
When attempting to start the Piper Recording Studio:
python3 -m piper_recording_studio

I received the following error: ImportError: cannot import name 'url_quote' from 'werkzeug.urls' 

The Werkzeug package released a new version on September 30th 2023, and appears to have removed a depedency.  I decided to downgrade the Werkzeug package from 3.0.0 to 2.3.7 and it appears to now work.

pip uninstall Werkzeug
pip install --upgrade Werkzeug==2.3.7

**Comment by synesthesiam** [comment]
Thanks, fixed!
