### ISSUE TITLE
What is the structure of the prompts?

### ISSUE THREAD

**Issue by Kentoseth** [rhasspy/piper-recording-studio#13]
I'm seeking to create my own set of prompts to then be recorded using PRS, but it is unclear what format they are using.

For example, https://github.com/rhasspy/piper-recording-studio/tree/master/prompts/Arabic%20(Egypt)_ar-EG

I can tell it is 3 different sources for the datasets, but within each set:

0000000001_0200000100

The numbering goes from normal increments to having a stepper: 00,01,02

What does this mean and does it matter?

**Comment by synesthesiam** [comment]
It doesn't matter. The format is `<id><TAB><text>` and all that matters is that the `<id>` is unique within the directory. It's probably best that it doesn't include any whitespace too.
