### ISSUE TITLE
How to add new language to Piper Recoding Studio?

### ISSUE THREAD

**Issue by pedjas** [rhasspy/piper-recording-studio#17]
I want to make TTS for language that is not listed in Piper Recording Studio. How can new language be added?

Is it enough to create language directory in prompts/ and create files in same manner as for other languages? 

Are there some requirements for phrasses in prompt files or that can be anything? Can I use phrases from existing language files and translate them to new language?

**Comment by synesthesiam** [comment]
Yes! Just make sure to follow the same format. I'd suggest also adding some numbers and short phrases that are common in the language (yes/no/thank you/etc).

Which language are you planning to add?

**Comment by pedjas** [comment]
Are there any rules of file contents, explanation on file naming sceheme and structure of files?

I see numbers showing up but it is not just ordered numbers, I see prefies in numbers (even different prefixes within same file). 

Generealy, while browsing langage folders i see there are some difference in naming and numbering.

What count of phrases is expected. Is ther eminimum requirement, Is there maximum limitation? Are thеre limitations per file?

Can I name files using serbian languages? Serbian language is bit complicated so one word can have number of variations depending of usage and I would like to use grammar terminology to organize variations in different files. I do not know English terminology so it is easier to use Serbian. 

I am going to try to add Serbian. I already prepared numbers file as that was easy to do. Can i add any number phrase or tehre are somе requirements? Can I add ordering numbers phrases like "first", "second", "third"...

How should I deal with phrases that are mant to be pronounced in normal voice, or sad voice, or as question, or angry voice or so?

If I talk someone into join me, how should we organise files so each works on his own set of phrases?

Sorry for so many questions but I could not find a single clue how to prepare new language.

**Comment by pedjas** [comment]
I have created repository to initiate creation of prompt files for Serbian language at https://github.com/pedjas/piper-recording-studio-prompts-serbian.

I've done this to avoid making mess in Piper Recording Studio until I am sure files are created proprly.

I already uploaded some files into repository and would apprecieate if files are checked for matching requirements to inclusion in Piper Recording Studio.

**Comment by pedjas** [comment]
I am still not sure if I prepared files properly.

**Comment by synesthesiam** [comment]
This looks good to me, thanks! You just need to change the directory name to have a dash (`-`) instead of an underscore before SR: `Serbian (Serbia)_rs-SR`

**Comment by pedjas** [comment]
That is great news! Thanks!
