### ISSUE TITLE
Errors on Exporting

### ISSUE THREAD

**Issue by Chreece** [rhasspy/piper-recording-studio#2]
The following ~~errors~~ warnings are coming direct after the exporting command:
```
/home/chreece/piper-recording-studio/export_dataset/__main__.py:77: UserWarning: PySoundFile failed. Trying audioread instead.
  audio_16khz, _sr = librosa.load(path=audio_path, sr=vad_sample_rate)
/usr/local/lib/python3.9/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
        Deprecated as of librosa version 0.10.0.
        It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/home/chreece/piper-recording-studio/export_dataset/__main__.py:77: UserWarning: PySoundFile failed. Trying audioread instead.
  audio_16khz, _sr = librosa.load(path=audio_path, sr=vad_sample_rate)
/usr/local/lib/python3.9/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
        Deprecated as of librosa version 0.10.0.
        It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/home/chreece/piper-recording-studio/export_dataset/__main__.py:77: UserWarning: PySoundFile failed. Trying audioread instead.
  audio_16khz, _sr = librosa.load(path=audio_path, sr=vad_sample_rate)
/usr/local/lib/python3.9/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
        Deprecated as of librosa version 0.10.0.
        It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/home/chreece/piper-recording-studio/export_dataset/__main__.py:89: UserWarning: PySoundFile failed. Trying audioread instead.
  audio, sample_rate = librosa.load(
/usr/local/lib/python3.9/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
        Deprecated as of librosa version 0.10.0.
        It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/home/chreece/voice-tools/piper/studio/output/el-GR/wav/4000000001_4000000300_CustomerService/4000000219.wav
/home/chreece/voice-tools/piper/studio/output/el-GR/wav/4000000001_4000000300_CustomerService/4000000147.wav
/home/chreece/piper-recording-studio/export_dataset/__main__.py:77: UserWarning: PySoundFile failed. Trying audioread instead.
  audio_16khz, _sr = librosa.load(path=audio_path, sr=vad_sample_rate)

```
but then seems that it does something:
```
/home/chreece/voice-tools/piper/studio/output/el-GR/wav/4000000001_4000000300_CustomerService/4000000023.wav
/home/chreece/voice-tools/piper/studio/output/el-GR/wav/4000000001_4000000300_CustomerService/4000000235.wav
/home/chreece/voice-tools/piper/studio/output/el-GR/wav/4000000001_4000000300_CustomerService/4000000073.wav
/home/chreece/voice-tools/piper/studio/output/el-GR/wav/4000000001_4000000300_CustomerService/4000000142.wav
/home/chreece/voice-tools/piper/studio/output/el-GR/wav/4000000001_4000000300_CustomerService/4000000192.wav
/home/chreece/voice-tools/piper/studio/output/el-GR/wav/4000000001_4000000300_CustomerService/4000000025.wav
/home/chreece/voice-tools/piper/studio/output/el-GR/wav/4000000001_4000000300_CustomerService/4000000161.wav
/home/chreece/voice-tools/piper/studio/output/el-GR/wav/4000000001_4000000300_CustomerService/4000000051.wav
/home/chreece/voice-tools/piper/studio/output/el-GR/wav/4000000001_4000000300_CustomerService/4000000057.wav
/home/chreece/voice-tools/piper/studio/output/el-GR/wav/4000000001_4000000300_CustomerService/4000000088.wav
/home/chreece/voice-tools/piper/studio/output/el-GR/wav/4000000001_4000000300_CustomerService/4000000210.wav
/home/chreece/voice-tools/piper/studio/output/el-GR/wav/4000000001_4000000300_CustomerService/4000000004.wav
/home/chreece/voice-tools/piper/studio/output/el-GR/wav/4000000001_4000000300_CustomerService/4000000202.wav
/home/chreece/voice-tools/piper/studio/output/el-GR/wav/4000000001_4000000300_CustomerService/4000000183.wav
/home/chreece/voice-tools/piper/studio/output/el-GR/wav/4000000001_4000000300_CustomerService/4000000198.wav
/home/chreece/voice-tools/piper/studio/output/el-GR/wav/4000000001_4000000300_CustomerService/4000000220.wav
/home/chreece/voice-tools/piper/studio/output/el-GR/wav/4000000001_4000000300_CustomerService/4000000086.wav
/home/chreece/voice-tools/piper/studio/output/el-GR/wav/4000000001_4000000300_CustomerService/4000000123.wav
/home/chreece/voice-tools/piper/studio/output/el-GR/wav/4000000001_4000000300_CustomerService/4000000185.wav
/home/chreece/voice-tools/piper/studio/output/el-GR/wav/4000000001_4000000300_CustomerService/4000000078.wav
/home/chreece/voice-tools/piper/studio/output/el-GR/wav/4000000001_4000000300_CustomerService/4000000100.wav
/home/chreece/voice-tools/piper/studio/output/el-GR/wav/4000000001_4000000300_CustomerService/4000000207.wav
/home/chreece/voice-tools/piper/studio/output/el-GR/wav/4000000001_4000000300_CustomerService/4000000201.wav
```
until I got some critical errors where it stays until i quit (ctr+c)

```
(python3:993184): GStreamer-CRITICAL **: 18:18:06.337: gst_poll_get_read_gpollfd: assertion 'set != NULL' failed

(python3:993184): GStreamer-CRITICAL **: 18:18:06.337: gst_bus_create_watch: assertion 'bus->priv->poll != NULL' failed

(python3:993184): GStreamer-CRITICAL **: 18:18:06.337: Creating bus watch failed

(python3:993184): GStreamer-CRITICAL **: 18:18:06.337: Could not add signal watch to bus bus2033
```

**Comment by synesthesiam** [comment]
I saw the warnings as well -- not sure what's going on with librosa, but searching around suggested they were waiting on an update to some underlying library.

The errors are confusing, though. Why is GStreamer involved?

**Comment by Chreece** [comment]
I hoped you had an answer! So there is no gstreamer involved?

**Comment by synesthesiam** [comment]
Not unless librosa is using it somehow 😄

**Comment by Chreece** [comment]
[There](https://github.com/librosa/librosa) are some mentions about gstreamer, i have also found [that](https://stackoverflow.com/questions/71117745/how-to-force-librosa-to-use-ffmpeg-instead-of-gstreamer)

**Comment by Chreece** [comment]
Here are some files causing the errors if you want to try them:
https://we.tl/t-iMCNodk0h9

```

/home/chreece/voice-tools/piper/studio/output/el-GR/wav/4000000001_4000000300_CustomerService/4000000021.wav

(python3:1693612): GStreamer-CRITICAL **: 20:01:04.359: gst_poll_get_read_gpollfd: assertion 'set != NULL' failed

(python3:1693612): GStreamer-CRITICAL **: 20:01:04.359: gst_bus_create_watch: assertion 'bus->priv->poll != NULL' failed

(python3:1693612): GStreamer-CRITICAL **: 20:01:04.363: Creating bus watch failed

(python3:1693612): GStreamer-CRITICAL **: 20:01:04.363: Could not add signal watch to bus bus2029

(python3:1693612): GStreamer-CRITICAL **: 20:01:04.362: gst_poll_get_read_gpollfd: assertion 'set != NULL' failed

(python3:1693612): GStreamer-CRITICAL **: 20:01:04.363: gst_bus_create_watch: assertion 'bus->priv->poll != NULL' failed

(python3:1693612): GStreamer-CRITICAL **: 20:01:04.369: Creating bus watch failed

(python3:1693612): GStreamer-CRITICAL **: 20:01:04.369: Could not add signal watch to bus bus2032
/home/chreece/voice-tools/piper/studio/output/el-GR/wav/4000000001_4000000300_CustomerService/4000000128.wav

(python3:1693612): GStreamer-CRITICAL **: 20:01:04.789: gst_poll_get_read_gpollfd: assertion 'set != NULL' failed

(python3:1693612): GStreamer-CRITICAL **: 20:01:04.789: gst_bus_create_watch: assertion 'bus->priv->poll != NULL' failed

(python3:1693612): GStreamer-CRITICAL **: 20:01:04.789: Creating bus watch failed

(python3:1693612): GStreamer-CRITICAL **: 20:01:04.789: Could not add signal watch to bus bus2037

(python3:1693612): GStreamer-CRITICAL **: 20:01:05.040: gst_poll_get_read_gpollfd: assertion 'set != NULL' failed

(python3:1693612): GStreamer-CRITICAL **: 20:01:05.041: gst_bus_create_watch: assertion 'bus->priv->poll != NULL' failed

(python3:1693612): GStreamer-CRITICAL **: 20:01:05.041: Creating bus watch failed

(python3:1693612): GStreamer-CRITICAL **: 20:01:05.041: Could not add signal watch to bus bus2041

```

**Comment by Gilimi-the-Grim** [comment]
I am a neophyte when it comes to python, but I have a similar issue when trying to export the audio recordings I have made.  I get the following error when I run this command.

`python3 -m export_dataset output/en-US/ /home/joeh/docker/piper-record/output/en-US/`

Here is the message.

`Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/joeh/docker/piper-recording-studio/export_dataset/__main__.py", line 8, in <module>
    import librosa
ModuleNotFoundError: No module named 'librosa'`

However, it does look like librosa is installed.

I know that isn't much to go on, but seems to be related to Chreese's comment.

Thanks,
Joe

**Comment by Chreece** [comment]
> However, it does look like librosa is installed.

 in the venv did you do:
`python3 -m pip install -r requirements_export.txt`?

**Comment by Gilimi-the-Grim** [comment]
Yes, and if I do a pip list it shows librosa is installed.  Below is the output of my pip list.  On another note, recorded in a separate docker container so the responses are in a different folder that the project being run.  I used the following command as listed in my previous post:

`python3 -m export_dataset output/en-US/ /home/joeh/docker/piper-record/output/en-US/`

and running piper-recording studiio from /home/joeh/docker/piper-recording-studio, does this matter.  Again, please overlook my tyro questions.

`(.venv) joeh@WJHildreth:~/docker/piper-recording-studio$ pip list
Package            Version
------------------ ------------
aiofiles           23.1.0
appdirs            1.4.4
audioread          3.0.0
blinker            1.5
certifi            2023.5.7
cffi               1.15.1
charset-normalizer 3.1.0
click              8.1.3
coloredlogs        15.0.1
decorator          5.1.1
flatbuffers        23.5.8
h11                0.14.0
h2                 4.1.0
hpack              4.0.0
humanfriendly      10.0
hypercorn          0.14.3
hyperframe         6.0.1
idna               3.4
importlib-metadata 6.6.0
itsdangerous       2.1.2
Jinja2             3.1.2
joblib             1.2.0
lazy_loader        0.2
librosa            0.10.0.post2
llvmlite           0.40.0
MarkupSafe         2.1.2
mpmath             1.3.0
msgpack            1.0.5
numba              0.57.0
numpy              1.24.3
onnxruntime        1.14.1
packaging          23.1
pip                23.1.2
pkg_resources      0.0.0
pooch              1.6.0
priority           2.0.0
protobuf           4.23.0
pycparser          2.21
quart              0.18.4
requests           2.30.0
scikit-learn       1.2.2
scipy              1.10.1
setuptools         44.0.0
soundfile          0.12.1
soxr               0.3.5
sympy              1.12
threadpoolctl      3.1.0
toml               0.10.2
typing_extensions  4.5.0
urllib3            2.0.2
Werkzeug           2.3.4
wsproto            1.2.0
zipp               3.15.0
`

Regards,
Joe

**Comment by Chreece** [comment]
> `python3 -m export_dataset output/en-US/ /home/joeh/docker/piper-record/output/en-US/`

> and running piper-recording studiio from /home/joeh/docker/piper-recording-studio, does this matter. 

the command should be run in the venv

**Comment by Gilimi-the-Grim** [comment]
I am sorry, I probably wasn't clear.  All the commands were run in the venv.

Joe

**Comment by Gilimi-the-Grim** [comment]
I just wanted to follow up, that the new release using ffmpeg worked fine for me.  Thank you Mr. Hansen fro fixing it.  :-)

Joe

**Comment by synesthesiam** [comment]
Switched to using `ffmpeg` for exporting since librosa is a mess :smile:
