### ISSUE TITLE
pip install -q piper-tts==1.2.0 >> No matching distribution found for piper-phonemize~=1.1.0

### ISSUE THREAD

**Issue by GreenAA** [rhasspy/piper-recording-studio#22]
SoniTranslate> pip install -q piper-tts==1.2.0
ERROR: Could not find a version that satisfies the requirement piper-phonemize~=1.1.0 (from piper-tts) (from versions: none)
ERROR: No matching distribution found for piper-phonemize~=1.1.0

**Comment by mylegitches** [comment]
I was able to get around this.  
 I am using WSL2 Ubuntu-20.04, but it 'should' work for you as well

Go into WSL instance, or regular linux terminal
 
```
git clone https://github.com/rhasspy/piper.git
cd piper/src/python
sudo apt update
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt install python3.8 python3.8-venv python3.8-distutils python3.8-dev
python3.8 -m venv .venv
source ./.venv/bin/activate
python3.8 -m pip install pip==24.0
pip3 install --upgrade wheel setuptools
sudo apt-get install espeak-ng
cd ~
sudo apt-get install python3-dev
```
I removed the piper-phonemize line from the requirements.txt file located at: ~\piper\src\python\requirements.txt
```
pip3 install -e .
pip install torchmetrics==0.11.0
pip install six
sudo apt update
sudo apt install build-essential
./build_monotonic_align.sh
```

**Comment by synesthesiam** [comment]
This repo is for Piper recording studio, not Piper itself.
