### ISSUE TITLE
FR: Enter custom phrases + MP3 upload

### ISSUE THREAD

**Issue by DunklerPhoenix** [rhasspy/piper-recording-studio#6]
Heho
It would be great if it were possible to enter custom phrases and then upload custom mp3 files to train the model.

This would make it possible to have popular voices like GLaDOS in my smart home :3

**Comment by synesthesiam** [comment]
Piper recording studio doesn't do any training, just recording. It's already possible to put together a dataset from any audio and train it: https://github.com/rhasspy/piper/blob/master/TRAINING.md

**Comment by DunklerPhoenix** [comment]
Thank you
